spring:
  application:
    name: feign-consumer
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true #禁止自已做为服务注册到服务上
    fetch-registry: true #禁止拿注册列表
    service-url:
       defaultZone: http://localhost:8761/eureka/ #注册中心地址
